pages:
  script:
    - mkdir -p public/dev/
    - git checkout master
    - cp repository.json public/repository.json
    - cp MudletPackageManager.xml public/MudletPackageManager.xml
    - git checkout dev
    - cp repository.json public/dev/repository.json
    - cp MudletPackageManager.xml public/dev/MudletPackageManager.xml
  artifacts:
    paths:
    - public
  only:
  - master
  - dev
